// GENERATED by scripts/gen-squelch-profile.py from profile/squelch.profile.
// Do not edit. Change the profile and regenerate; hygiene_check.sh enforces this.

namespace AudioBridge {
  static class SquelchProfile {
    public const string Id       = "pcm48-stereo-s16-squelch-v1";
    public const string Hash     = "a7cd2ed96286";
    public const int SampleRate  = 48000;
    public const int Channels    = 2;
    public const int FrameBytes  = 4;
    public const short SilencePeak = 16;
    public const int ConfirmFrames = 12000;
    public const int HeartbeatMs   = 2000;

    // Inclusive on both channels, compared after promotion to int so that short.MinValue
    // cannot overflow its own negation.
    public static bool FrameIsSilent(short left, short right) {
      int l = left < 0 ? -(int)left : left;
      int r = right < 0 ? -(int)right : right;
      return l <= SilencePeak && r <= SilencePeak;
    }
  }
}
