// GENERATED by scripts/gen-squelch-profile.py from profile/squelch.profile.
// Do not edit. Change the profile and regenerate; hygiene_check.sh enforces this.

enum SquelchProfile {
    static let id            = "pcm48-stereo-s16-squelch-v1"
    static let hash          = "a7cd2ed96286"
    static let sampleRate    = 48000
    static let channels      = 2
    static let frameBytes    = 4
    static let silencePeak   : Int32 = 16
    static let confirmFrames = 12000
    static let heartbeatMs   = 2000

    /// Inclusive on both channels, compared after promotion to a wider signed type so that
    /// -32768 cannot overflow its own negation.
    @inline(__always)
    static func frameIsSilent(_ left: Int16, _ right: Int16) -> Bool {
        return abs(Int32(left)) <= silencePeak && abs(Int32(right)) <= silencePeak
    }
}
