#!/usr/bin/env python3
"""Generate the Swift and C# squelch-profile bindings from profile/squelch.profile.

One definition, two languages, one hash. Run after editing the profile; hygiene_check.sh
fails the build if the committed bindings do not match a fresh generation.

  python3 scripts/gen-squelch-profile.py           # write the bindings
  python3 scripts/gen-squelch-profile.py --check   # exit 1 if they are stale
"""
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PROFILE = ROOT / "profile" / "squelch.profile"
SWIFT = ROOT / "mac" / "SquelchProfile.swift"
CSHARP = ROOT / "windows" / "lib" / "SquelchProfile.cs"

REQUIRED = ["profile_id", "sample_rate", "channels", "frame_bytes",
            "silence_peak", "confirm_frames", "heartbeat_ms"]


def load():
    values, order = {}, []
    for raw in PROFILE.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            sys.exit("malformed profile line (no '='): %r" % raw)
        key, _, value = line.partition("=")
        key, value = key.strip(), value.strip()
        if key in values:
            sys.exit("duplicate profile key: %s" % key)
        values[key], _ = value, order.append(key)
    missing = [k for k in REQUIRED if k not in values]
    if missing:
        sys.exit("profile is missing required keys: %s" % ", ".join(missing))
    extra = [k for k in order if k not in REQUIRED]
    if extra:
        sys.exit("profile has unknown keys (add them to REQUIRED first): %s" % ", ".join(extra))
    # Canonical form for the hash: required keys, fixed order, no comments or whitespace.
    canonical = "\n".join("%s=%s" % (k, values[k]) for k in REQUIRED)
    digest = hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:12]
    return values, digest


BANNER = ("// GENERATED by scripts/gen-squelch-profile.py from profile/squelch.profile.\n"
          "// Do not edit. Change the profile and regenerate; hygiene_check.sh enforces this.\n")


def swift(v, digest):
    return BANNER + """
enum SquelchProfile {
    static let id            = "%s"
    static let hash          = "%s"
    static let sampleRate    = %s
    static let channels      = %s
    static let frameBytes    = %s
    static let silencePeak   : Int32 = %s
    static let confirmFrames = %s
    static let heartbeatMs   = %s

    /// Inclusive on both channels, compared after promotion to a wider signed type so that
    /// -32768 cannot overflow its own negation.
    @inline(__always)
    static func frameIsSilent(_ left: Int16, _ right: Int16) -> Bool {
        return abs(Int32(left)) <= silencePeak && abs(Int32(right)) <= silencePeak
    }
}
""" % (v["profile_id"], digest, v["sample_rate"], v["channels"], v["frame_bytes"],
       v["silence_peak"], v["confirm_frames"], v["heartbeat_ms"])


def csharp(v, digest):
    return BANNER + """
namespace AudioBridge {
  static class SquelchProfile {
    public const string Id       = "%s";
    public const string Hash     = "%s";
    public const int SampleRate  = %s;
    public const int Channels    = %s;
    public const int FrameBytes  = %s;
    public const short SilencePeak = %s;
    public const int ConfirmFrames = %s;
    public const int HeartbeatMs   = %s;

    // Inclusive on both channels, compared after promotion to int so that short.MinValue
    // cannot overflow its own negation.
    public static bool FrameIsSilent(short left, short right) {
      int l = left < 0 ? -(int)left : left;
      int r = right < 0 ? -(int)right : right;
      return l <= SilencePeak && r <= SilencePeak;
    }
  }
}
""" % (v["profile_id"], digest, v["sample_rate"], v["channels"], v["frame_bytes"],
       v["silence_peak"], v["confirm_frames"], v["heartbeat_ms"])


def main():
    values, digest = load()
    outputs = [(SWIFT, swift(values, digest)), (CSHARP, csharp(values, digest))]
    if "--check" in sys.argv:
        stale = [p.name for p, text in outputs
                 if not p.exists() or p.read_text() != text]
        if stale:
            print("squelch profile bindings are stale: %s" % ", ".join(stale))
            print("run: python3 scripts/gen-squelch-profile.py")
            return 1
        print("squelch profile bindings match (%s %s)" % (values["profile_id"], digest))
        return 0
    for path, text in outputs:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
        print("wrote %s" % path.relative_to(ROOT))
    print("profile %s hash %s" % (values["profile_id"], digest))
    return 0


if __name__ == "__main__":
    sys.exit(main())
