// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyParams(arg1:number,arg2:number,arg3:number,arg4:number):Promise<string>;

export function CheckDeps():Promise<Array<string>>;

export function DiscoverPeers():Promise<Array<main.PeerInfo>>;

export function GetConfig():Promise<main.Config>;

export function GetStatus():Promise<main.Status>;

export function SetAutoStart(arg1:boolean):Promise<string>;

export function SetDirection(arg1:string):Promise<string>;

export function SetPeerIP(arg1:string):Promise<string>;

export function SetRole(arg1:string):Promise<string>;

export function SetVolume(arg1:number):Promise<string>;

export function Start():Promise<string>;

export function Stop():Promise<string>;

export function Toggle():Promise<string>;

export function Verify():Promise<string>;
