// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyParams(arg1, arg2, arg3) {
  return window['go']['main']['App']['ApplyParams'](arg1, arg2, arg3);
}

export function CheckDeps() {
  return window['go']['main']['App']['CheckDeps']();
}

export function DiscoverPeers() {
  return window['go']['main']['App']['DiscoverPeers']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetDirection(arg1) {
  return window['go']['main']['App']['SetDirection'](arg1);
}

export function SetPeerIP(arg1) {
  return window['go']['main']['App']['SetPeerIP'](arg1);
}

export function SetRole(arg1) {
  return window['go']['main']['App']['SetRole'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['main']['App']['SetVolume'](arg1);
}

export function Start() {
  return window['go']['main']['App']['Start']();
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}

export function Toggle() {
  return window['go']['main']['App']['Toggle']();
}

export function Verify() {
  return window['go']['main']['App']['Verify']();
}
